version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
